mysite/myapp/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views

app_name= 'myapp'

urlpatterns = [
    path('', views.index,name='index'),
    path('products/', views.products,name='products'),
    path('book/<int:id>/', views.details, name='details'),
    path('add/', views.add_book, name='add_book'),
    path('update/<int:id>/', views.update_book, name='update'),
    path('delete/<int:id>/', views.delete_book, name='delete')
]
    

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views
from .import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/myapp/models.py
from django.db import models


class Book(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    price = models.IntegerField()
    book_image = models.ImageField(default='default_book.jpg',upload_to='book_images/')

mysite/myapp/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:    
        model = Book
        fields = ['name', 'description', 'book_image', 'price']

mysite/myapp/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Book
from .forms import BookForm


def index(request):
    book_list = Book.objects.all()
    context = {
        'book_list':book_list
    }
    return render(request, 'myapp/index.html',context)

def details(request,id):
    book = Book.objects.get(id=id)
    return render(request, "myapp/detail.html",{'book': book})

def products(request):
    return HttpResponse('There are some Products:')

def add_book(request):
    if request.method == "POST":
        name = request.POST.get('name')
        description = request.POST.get('description')
        price = request.POST.get('price')
        
        if 'book_image' in request.FILES:
            book_image = request.FILES['book_image']
        else:
            book_image = None  

        book = Book(name=name, description=description, price=price, book_image=book_image)

        book.save()

        return HttpResponseRedirect('/')  

    return render(request, 'myapp/add_book.html')

def update_book(request,id):
    book = Book.objects.get(id=id)
    form = BookForm(request.POST or None, request.FILES, instance=book)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'myapp/edit_book.html',{'form':form,'book':book})

def delete_book(request,id):
    book = Book.objects.get(id=id)
    if request.method == "POST":
        book.delete()
        return HttpResponseRedirect('/')  
    return render(request, 'myapp/delete.html')

mysite/myapp/templates/myapp/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <form method="POST" enctype="multipart/form-data" class="row g-3">
        {% csrf_token %}
        <div class="col-auto">
            <div class="mb-3">
                <label for="inputPassword2" class="visually-hidden">Name</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="Name of the Book">
            </div>
            <div class="mb-3">
                <label for="inputPassword2" class="visually-hidden">Description</label>
                <input type="text" name="description" class="form-control" id="description" placeholder="Description of the Book">
            </div>
            <div class="mb-3">
                <label for="inputPassword2" class="visually-hidden">Price</label>
                <input type="text" name="price" class="form-control" id="price" placeholder="Price of the Book">
            </div> 
            <div class="mb-3">
                <label for="formFile" class="form-label">Select Book Image</label>
                <input class="form-control" name="book_image" type="file" id="book_image">
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-primary mb-3">Add Book</button>
            </div>
        </div>
    </form>
</body>
</html>

mysite/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
            <link rel="stylesheet" href="{% static 'myapp/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'myapp:index' %}">Book Store</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                {% block body_main %}
                    
                {% endblock %}
            </ul>
          </div>
        </div>
      </nav>
      <div>
        {% block body_detail %}
                    
        {% endblock %}
      </div>
</body>
</html>

mysite/myapp/templates/myapp/delete.html
<form method="POST">
    {% csrf_token %}
    are you sure?
    <input type="submit" name="" id="">

</form>

mysite/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}]

{% block body_detail %}

<img width="100" height="100" src="{{book.book_image.url}}">
<h2>{{book.name}}</h2>
<br>
<h4>{{book.description}} </h4>
<br>
<h6>{{book.price}}</h6>
<br>
<a href="{% url 'myapp:delete' book.id %}" type="button" class="btn btn-danger">Delete</a>   
<a href="{% url 'myapp:update' book.id %}" type="button" class="btn btn-warning">Edit</a>         
{% endblock %}

mysite/myapp/templates/myapp/edit_book.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="button", name="", id="">

</form>

mysite/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body_main %}

{% for book in book_list %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:details' book.id %}">
            {{ book.name }}
        </a>
    </li>   
{% endfor %}

{% endblock %}